package org.treeWare.mySql.operator

import org.treeWare.metaModel.FieldType

const val CREATED_ON_COLUMN_NAME = "created_on_"
const val CREATED_ON_COLUMN_TYPE = "TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)"
val CREATED_ON_COLUMN_SQL_TYPE = FieldType.TIMESTAMP

const val UPDATED_ON_COLUMN_NAME = "updated_on_"
const val UPDATED_ON_COLUMN_TYPE = "TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)"
val UPDATED_ON_COLUMN_SQL_TYPE = FieldType.TIMESTAMP

const val FIELD_PATH_COLUMN_NAME = "field_path_"
const val FIELD_PATH_COLUMN_TYPE = "TEXT"
val FIELD_PATH_COLUMN_SQL_TYPE = FieldType.STRING

const val SINGLETON_KEY_COLUMN_NAME = "singleton_key_"
const val SINGLETON_KEY_COLUMN_TYPE = "INT UNSIGNED"
val SINGLETON_KEY_COLUMN_SQL_TYPE = FieldType.INT8
const val SINGLETON_KEY_COLUMN_VALUE = 0